apiVersion: v1
kind: Pod
metadata:
  name: node.example.com
  labels:
    app: captain-clapp 
spec:
  containers:
  - name: k8s-demo
    image: vinga2805/mynodejsapp 
    ports:
    - name: nodejs-port
      containerPort: 3000
