version: '3.3'
services:
   drupal:
      image: drupal:latest
      ports:
        - '80:80'
      volumes:
        - drupal-modules:/var/www/html/modules 
        - drupal-profiles:/var/www/html/profiles
        - drupal-sites:/var/www/html/sites
        - drupal-themes:/var/www/html/themes
   db:
    image: postgres:latest
    volumes:
        - pg_data:/var/lib/postgresql/data
    environment:
            POSTGRES_PASSWORD: test123
volumes:
    drupal-modules:
    drupal-profiles:
    drupal-sites:
    drupal-themes:
    pg_data:
